### ISSUE TITLE
consider use ordered list for Markdown document

### ISSUE THREAD

**Issue by notcome** [notcome/Constitution.PRC#2]
With CSS 2.1 Counters:

``` CSS
ol { counter-reset: item }
li { display: block }
li:before {
  content: "第" counter(item, cjk-ideographic) "条、";
  counter-increment: item;
}
```
